version: "3.9"
services:
#==== NGINX ===================================================================#
  #nginx:
   # container_name: nginx
   # build: containers/nginx
   # image: nginx
    #env_file: .env
#    depends_on:
#     - postgresql
    #ports:
     # - 80:80
     # - 443:443
    #networks:
    #  - transcendence
   # restart: unless-stopped

#==== NODEJS ==================================================================#
  front:
    container_name: front
    build: containers/front
    image: front
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - ./apps/front:/var/www/html/front
    networks:
      - transcendence
    stdin_open: true
    restart: unless-stopped

  back:
    container_name: back
    build: containers/back
    image: back
    env_file: .env
    depends_on:
      - db
    ports:
      - 3030:3030
    volumes:
      - ./apps/back:/var/www/html/back
    networks:
      - transcendence
    stdin_open: true
    restart: unless-stopped
#==== POSTGRESQL ==============================================================#
  db:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transcendence
    networks:
      - transcendence

#============================================================================#
networks:
  transcendence:
    name: transcendence
    driver: bridge
