import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
	<div className={styles.container}>
		<Head>
			<title>Transcendence</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		<main className={styles.main}>
			<h1 className={styles.title}>
			Welcome to <a href="">Transcendence</a>
			</h1>

			<p className={styles.description}>Coming soon </p>
		</main>

		<footer className={styles.footer}>
			Made with love by{' '},
			<a href="">acoezard</a>,{' '}
			<a href="">mboy</a> and {' '}
			<a href="">jstopka</a>.
		</footer>
	</div>
  )
}

export default Home
